// GENERATED by scripts/sync-runtimes.mjs — do not edit by hand.
// Re-generate with: pnpm sync:runtimes
//
// Source: OpenCoven/coven-runtimes canonical registry index
//   ref:      main
//   blob sha: 051805ae24056d3efee0b93b73fee75e0d737b52
//
// Every entry passed coven-runtimes acceptance (conformance + review), so
// Cave treats these as trusted runtimes (see harness-adapters.ts). New
// runtimes get a generic glyph until someone adds a brand mark in
// runtime-logo.tsx — that polish stays a deliberate manual step.

export type RegistryRuntimeCapabilities = {
  stream: boolean;
  preassignedSessionId: boolean;
  think: boolean;
  speed: boolean;
};

export type RegistryRuntime = {
  id: string;
  label: string;
  binary: string;
  installHint: string;
  version: string;
  homepage?: string;
  description?: string;
  /** CLI flag that forwards a model id, when the runtime supports one. */
  modelFlag: string | null;
  capabilities: RegistryRuntimeCapabilities;
  /** The full `$COVEN_HOME/adapters/<id>.json` document for this runtime. */
  adapterManifest: unknown;
};

export const REGISTRY_SOURCE = {
  repo: "OpenCoven/coven-runtimes",
  ref: "main",
  blobSha: "051805ae24056d3efee0b93b73fee75e0d737b52",
} as const;

export const REGISTRY_RUNTIMES: RegistryRuntime[] = [
  {
    "id": "copilot",
    "label": "GitHub Copilot CLI",
    "binary": "copilot",
    "installHint": "npm install -g @github/copilot (or `brew install copilot-cli`), then run `copilot login` and ensure `copilot` is on PATH.",
    "version": "1.0.0",
    "homepage": "https://docs.github.com/en/copilot/concepts/agents/about-copilot-cli",
    "description": "GitHub Copilot CLI adapter. One-shot via `-s -p`, interactive via `-i`, JSONL streaming via `--output-format json --stream on`, session pre-assignment/resume via `--session-id`/`--resume`. Permission mapping uses the argv-list sandbox form because Copilot's flags are boolean/repeatable (`--allow-all`; `--deny-tool write --deny-tool shell`) rather than a single `--flag value` pair.",
    "modelFlag": "--model",
    "capabilities": {
      "stream": true,
      "preassignedSessionId": true,
      "think": false,
      "speed": false
    },
    "adapterManifest": {
      "adapters": [
        {
          "id": "copilot",
          "label": "GitHub Copilot CLI",
          "executable": "copilot",
          "interactive_prompt_prefix_args": [
            "-i"
          ],
          "non_interactive_prompt_prefix_args": [
            "-s",
            "-p"
          ],
          "install_hint": "npm install -g @github/copilot (or `brew install copilot-cli`), then run `copilot login` and ensure `copilot` is on PATH.",
          "model_flag": "--model",
          "capabilities": {
            "stream": true,
            "preassigned_session_id": true,
            "think": false,
            "speed": false
          },
          "sandbox": {
            "full_args": [
              "--allow-all"
            ],
            "read_only_args": [
              "--deny-tool",
              "write",
              "--deny-tool",
              "shell"
            ]
          },
          "stream_args": {
            "prefix_args": [
              "--output-format",
              "json",
              "--stream",
              "on",
              "-p"
            ],
            "session_id_flag": "--session-id",
            "resume_flag": "--resume"
          },
          "version": "1.0.0",
          "homepage": "https://docs.github.com/en/copilot/concepts/agents/about-copilot-cli",
          "description": "GitHub Copilot CLI adapter. One-shot via `-s -p`, interactive via `-i`, JSONL streaming via `--output-format json --stream on`, session pre-assignment/resume via `--session-id`/`--resume`. Permission mapping uses the argv-list sandbox form because Copilot's flags are boolean/repeatable (`--allow-all`; `--deny-tool write --deny-tool shell`) rather than a single `--flag value` pair."
        }
      ]
    }
  },
  {
    "id": "coven-code",
    "label": "Coven Code",
    "binary": "coven-code",
    "installHint": "npm install -g @opencoven/coven-code (or download a release archive from https://github.com/OpenCoven/coven-code/releases), then ensure `coven-code` is on PATH.",
    "version": "1.0.1",
    "homepage": "https://github.com/OpenCoven/coven-code",
    "description": "Coven Code adapter. One-shot via `--print <prompt>`, JSONL streaming via `--print --input-format stream-json --output-format stream-json` (long-lived: one turn per stdin user frame, exits on stdin EOF; the positional prompt is ignored in this mode, matching Claude Code). Session pre-assignment/resume via `--session-id`/`--resume`. Think maps to `--thinking <TOKENS>`, speed to `--effort <LEVEL>`. Interactive launches must not append a prompt: a positional prompt switches coven-code into print mode.",
    "modelFlag": "--model",
    "capabilities": {
      "stream": true,
      "preassignedSessionId": true,
      "think": true,
      "speed": true
    },
    "adapterManifest": {
      "adapters": [
        {
          "id": "coven-code",
          "label": "Coven Code",
          "executable": "coven-code",
          "interactive_prompt_prefix_args": [],
          "non_interactive_prompt_prefix_args": [
            "--print"
          ],
          "install_hint": "npm install -g @opencoven/coven-code (or download a release archive from https://github.com/OpenCoven/coven-code/releases), then ensure `coven-code` is on PATH.",
          "system_prompt_flag": "--append-system-prompt",
          "model_flag": "--model",
          "capabilities": {
            "stream": true,
            "preassigned_session_id": true,
            "think": true,
            "speed": true
          },
          "sandbox": {
            "flag": "--permission-mode",
            "full": "bypass-permissions",
            "read_only": "plan"
          },
          "stream_args": {
            "prefix_args": [
              "--print",
              "--input-format",
              "stream-json",
              "--output-format",
              "stream-json"
            ],
            "session_id_flag": "--session-id",
            "resume_flag": "--resume"
          },
          "version": "1.0.1",
          "homepage": "https://github.com/OpenCoven/coven-code",
          "description": "Coven Code adapter. One-shot via `--print <prompt>`, JSONL streaming via `--print --input-format stream-json --output-format stream-json` (long-lived: one turn per stdin user frame, exits on stdin EOF; the positional prompt is ignored in this mode, matching Claude Code). Session pre-assignment/resume via `--session-id`/`--resume`. Think maps to `--thinking <TOKENS>`, speed to `--effort <LEVEL>`. Interactive launches must not append a prompt: a positional prompt switches coven-code into print mode."
        }
      ]
    }
  },
  {
    "id": "hermes",
    "label": "Hermes Agent",
    "binary": "hermes-coven",
    "installHint": "Install Hermes Agent, add it to PATH, install the hermes-coven shim, and complete Hermes setup before using this adapter.",
    "version": "1.0.1",
    "description": "Reference adapter — mirrors coven's built-in Hermes recipe. A plain one-shot runtime with baseline capabilities. Uses the hermes-coven shim so the harness's trailing positional prompt is remapped to hermes chat's -q/--query flag (hermes has no positional prompt slot).",
    "modelFlag": null,
    "capabilities": {
      "stream": false,
      "preassignedSessionId": false,
      "think": false,
      "speed": false
    },
    "adapterManifest": {
      "adapters": [
        {
          "id": "hermes",
          "label": "Hermes Agent",
          "executable": "hermes-coven",
          "interactive_prompt_prefix_args": [
            "chat",
            "--source",
            "coven"
          ],
          "non_interactive_prompt_prefix_args": [
            "chat",
            "--source",
            "coven",
            "-Q"
          ],
          "install_hint": "Install Hermes Agent, add it to PATH, install the hermes-coven shim, and complete Hermes setup before using this adapter.",
          "capabilities": {
            "stream": false,
            "preassigned_session_id": false,
            "think": false,
            "speed": false
          },
          "version": "1.0.1",
          "description": "Reference adapter — mirrors coven's built-in Hermes recipe. A plain one-shot runtime with baseline capabilities. Uses the hermes-coven shim so the harness's trailing positional prompt is remapped to hermes chat's -q/--query flag (hermes has no positional prompt slot)."
        }
      ]
    }
  },
  {
    "id": "opencode",
    "label": "OpenCode",
    "binary": "opencode",
    "installHint": "Install OpenCode from https://opencode.ai/docs/cli (e.g. `npm i -g opencode-ai`) and ensure `opencode` resolves on PATH. Verify with `opencode run --help` — the similarly-named Go app some package managers ship has no `run` subcommand and will not work.",
    "version": "0.1.0",
    "homepage": "https://opencode.ai",
    "description": "OpenCode runtime adapter for Coven. Drives `opencode run` in non-interactive mode; system prompts and tools are configured via the OpenCode project config (AGENTS.md / opencode.json), not via CLI flags.",
    "modelFlag": "--model",
    "capabilities": {
      "stream": false,
      "preassignedSessionId": false,
      "think": false,
      "speed": false
    },
    "adapterManifest": {
      "adapters": [
        {
          "id": "opencode",
          "label": "OpenCode",
          "executable": "opencode",
          "interactive_prompt_prefix_args": [],
          "non_interactive_prompt_prefix_args": [
            "run"
          ],
          "install_hint": "Install OpenCode from https://opencode.ai/docs/cli (e.g. `npm i -g opencode-ai`) and ensure `opencode` resolves on PATH. Verify with `opencode run --help` — the similarly-named Go app some package managers ship has no `run` subcommand and will not work.",
          "model_flag": "--model",
          "capabilities": {
            "stream": false,
            "preassigned_session_id": false,
            "think": false,
            "speed": false
          },
          "version": "0.1.0",
          "homepage": "https://opencode.ai",
          "description": "OpenCode runtime adapter for Coven. Drives `opencode run` in non-interactive mode; system prompts and tools are configured via the OpenCode project config (AGENTS.md / opencode.json), not via CLI flags."
        }
      ]
    }
  }
];
