export type WorkspaceMode =
  | "agents"
  | "home"
  | "chat"
  | "groupchat"
  | "board"
  | "calendar"
  | "inbox"
  | "browser"
  | "github"
  | "roles"
  | "marketplace"
  | "flow"
  | "submissions"
  | "capabilities"
  | "familiar-work-queue"
  | "journal";
