// Tests for scripts/sync-runtimes.mjs — fixture-driven, no network.
import assert from "node:assert/strict";
import { CAVE_EXCLUDED_RUNTIME_IDS, compareSemver, pickAcceptedRuntimes, renderModule, validateAdapter } from "./sync-runtimes.mjs";

const adapter = (id, extra = {}) => ({
  id,
  label: `${id} label`,
  executable: id,
  install_hint: `install ${id}`,
  capabilities: { stream: true, preassigned_session_id: false, think: false, speed: false },
  ...extra,
});

const entry = (id, version, extra = {}) => ({ version, adapter: adapter(id), ...extra });

// ── semver ordering ──────────────────────────────────────────────────────────
assert.ok(compareSemver("1.2.0", "1.1.9") > 0, "minor bump wins");
assert.ok(compareSemver("0.10.0", "0.9.1") > 0, "numeric (not lexical) compare");
assert.ok(compareSemver("1.0.0", "1.0.0-rc.1") > 0, "release beats prerelease");
assert.equal(compareSemver("2.0.0", "2.0.0"), 0, "equal versions compare equal");
// Semver §11.4 prerelease precedence (review finding: plain string compare
// ranked rc.10 below rc.9).
assert.ok(compareSemver("1.0.0-rc.10", "1.0.0-rc.9") > 0, "numeric prerelease identifiers compare numerically");
assert.ok(compareSemver("1.0.0-beta.11", "1.0.0-beta.2") > 0, "beta.11 > beta.2");
assert.ok(compareSemver("1.0.0-alpha", "1.0.0-alpha.1") < 0, "fewer identifiers lose the tie");
assert.ok(compareSemver("1.0.0-alpha.1", "1.0.0-alpha.beta") < 0, "numeric identifiers rank below alphanumeric");
assert.ok(compareSemver("1.0.0-beta", "1.0.0-alpha") > 0, "alphanumeric identifiers compare lexically");
// Build metadata is ignored for precedence (semver §10) — review finding:
// "+x" leaked into identifier comparison and outranked numeric identifiers.
assert.ok(compareSemver("1.0.0-rc.2", "1.0.0-rc.1+x") > 0, "build metadata never outranks a newer prerelease");
assert.equal(compareSemver("1.0.0-rc.1+b", "1.0.0-rc.1"), 0, "build metadata is precedence-invisible");
assert.equal(compareSemver("2.0.0+build.5", "2.0.0"), 0, "release build metadata is precedence-invisible");

// ── latest non-yanked pick ───────────────────────────────────────────────────
{
  const picked = pickAcceptedRuntimes({
    format: "1",
    runtimes: {
      zeta: [entry("zeta", "1.0.0")],
      alpha: [entry("alpha", "1.0.0"), entry("alpha", "1.2.0"), entry("alpha", "1.1.0")],
    },
  });
  assert.deepEqual(
    picked.map((p) => `${p.id}@${p.version}`),
    ["alpha@1.2.0", "zeta@1.0.0"],
    "picks the highest version per runtime, sorted by id",
  );
}

{
  const picked = pickAcceptedRuntimes({
    format: "1",
    runtimes: {
      a: [entry("a", "1.0.0"), entry("a", "2.0.0", { yanked: true })],
      gone: [entry("gone", "1.0.0", { yanked: true })],
    },
  });
  assert.deepEqual(
    picked.map((p) => `${p.id}@${p.version}`),
    ["a@1.0.0"],
    "yanked versions are skipped for latest; fully-yanked runtimes are omitted",
  );
}

// ── Cave-side policy exclusions ──────────────────────────────────────────────
{
  assert.ok(CAVE_EXCLUDED_RUNTIME_IDS.has("coven-code"), "coven-code is policy-excluded");
  const picked = pickAcceptedRuntimes({
    format: "1",
    runtimes: {
      "coven-code": [entry("coven-code", "1.0.0")],
      keeper: [entry("keeper", "1.0.0")],
    },
  });
  assert.deepEqual(
    picked.map((p) => p.id),
    ["keeper"],
    "policy-excluded runtimes never reach the generated module, even when accepted upstream",
  );
}

// ── validation gates ─────────────────────────────────────────────────────────
assert.throws(
  () => pickAcceptedRuntimes({ format: "2", runtimes: {} }),
  /unsupported registry index format/,
  "unknown index format is a hard error",
);
assert.throws(
  () =>
    pickAcceptedRuntimes({
      format: "1",
      runtimes: { bad: [{ version: "1.0.0", adapter: { id: "bad", label: "", executable: "bad", install_hint: "x" } }] },
    }),
  /label must be a non-empty string/,
  "malformed adapters never compile into Cave",
);
assert.deepEqual(validateAdapter("x", adapter("y")), [
  'x: adapter.id "y" does not match its registry key',
], "id/key mismatch is caught");
assert.ok(
  validateAdapter("x", adapter("x", { non_interactive_prompt_prefix_args: [1] })).length > 0,
  "non-string args are rejected",
);

// ── deterministic rendering ──────────────────────────────────────────────────
{
  const picked = pickAcceptedRuntimes({
    format: "1",
    runtimes: { one: [entry("one", "1.0.0", { adapter: adapter("one", { model_flag: "--model", homepage: "https://x" }) })] },
  });
  const source = { repo: "OpenCoven/coven-runtimes", ref: "main", blobSha: "abc123" };
  const first = renderModule(picked, source);
  const second = renderModule(picked, source);
  assert.equal(first, second, "identical inputs render byte-identical modules");
  assert.match(first, /GENERATED by scripts\/sync-runtimes\.mjs/, "generated banner present");
  assert.match(first, /blob sha: abc123/, "provenance pins the index blob sha");
  assert.match(first, /"modelFlag": "--model"/, "model flag carried through");
  assert.match(first, /"preassignedSessionId": false/, "capabilities normalized to camelCase");
  assert.match(first, /"adapterManifest": \{/, "full adapter manifest embedded for scaffolding");
}

console.log("sync-runtimes.test.mjs: ok");
