// Tests for scripts/sync-runtimes.mjs — fixture-driven, no network.
import assert from "node:assert/strict";
import { compareSemver, pickAcceptedRuntimes, renderModule, validateAdapter } from "./sync-runtimes.mjs";

const adapter = (id, extra = {}) => ({
  id,
  label: `${id} label`,
  executable: id,
  install_hint: `install ${id}`,
  capabilities: { stream: true, preassigned_session_id: false, think: false, speed: false },
  ...extra,
});

const entry = (id, version, extra = {}) => ({ version, adapter: adapter(id), ...extra });

// ── semver ordering ──────────────────────────────────────────────────────────
assert.ok(compareSemver("1.2.0", "1.1.9") > 0, "minor bump wins");
assert.ok(compareSemver("0.10.0", "0.9.1") > 0, "numeric (not lexical) compare");
assert.ok(compareSemver("1.0.0", "1.0.0-rc.1") > 0, "release beats prerelease");
assert.equal(compareSemver("2.0.0", "2.0.0"), 0, "equal versions compare equal");

// ── latest non-yanked pick ───────────────────────────────────────────────────
{
  const picked = pickAcceptedRuntimes({
    format: "1",
    runtimes: {
      zeta: [entry("zeta", "1.0.0")],
      alpha: [entry("alpha", "1.0.0"), entry("alpha", "1.2.0"), entry("alpha", "1.1.0")],
    },
  });
  assert.deepEqual(
    picked.map((p) => `${p.id}@${p.version}`),
    ["alpha@1.2.0", "zeta@1.0.0"],
    "picks the highest version per runtime, sorted by id",
  );
}

{
  const picked = pickAcceptedRuntimes({
    format: "1",
    runtimes: {
      a: [entry("a", "1.0.0"), entry("a", "2.0.0", { yanked: true })],
      gone: [entry("gone", "1.0.0", { yanked: true })],
    },
  });
  assert.deepEqual(
    picked.map((p) => `${p.id}@${p.version}`),
    ["a@1.0.0"],
    "yanked versions are skipped for latest; fully-yanked runtimes are omitted",
  );
}

// ── validation gates ─────────────────────────────────────────────────────────
assert.throws(
  () => pickAcceptedRuntimes({ format: "2", runtimes: {} }),
  /unsupported registry index format/,
  "unknown index format is a hard error",
);
assert.throws(
  () =>
    pickAcceptedRuntimes({
      format: "1",
      runtimes: { bad: [{ version: "1.0.0", adapter: { id: "bad", label: "", executable: "bad", install_hint: "x" } }] },
    }),
  /label must be a non-empty string/,
  "malformed adapters never compile into Cave",
);
assert.deepEqual(validateAdapter("x", adapter("y")), [
  'x: adapter.id "y" does not match its registry key',
], "id/key mismatch is caught");
assert.ok(
  validateAdapter("x", adapter("x", { non_interactive_prompt_prefix_args: [1] })).length > 0,
  "non-string args are rejected",
);

// ── deterministic rendering ──────────────────────────────────────────────────
{
  const picked = pickAcceptedRuntimes({
    format: "1",
    runtimes: { one: [entry("one", "1.0.0", { adapter: adapter("one", { model_flag: "--model", homepage: "https://x" }) })] },
  });
  const source = { repo: "OpenCoven/coven-runtimes", ref: "main", blobSha: "abc123" };
  const first = renderModule(picked, source);
  const second = renderModule(picked, source);
  assert.equal(first, second, "identical inputs render byte-identical modules");
  assert.match(first, /GENERATED by scripts\/sync-runtimes\.mjs/, "generated banner present");
  assert.match(first, /blob sha: abc123/, "provenance pins the index blob sha");
  assert.match(first, /"modelFlag": "--model"/, "model flag carried through");
  assert.match(first, /"preassignedSessionId": false/, "capabilities normalized to camelCase");
  assert.match(first, /"adapterManifest": \{/, "full adapter manifest embedded for scaffolding");
}

console.log("sync-runtimes.test.mjs: ok");
