// @ts-nocheck
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const executions = readFileSync(new URL("./flow-executions.tsx", import.meta.url), "utf8");
const view = readFileSync(new URL("./flow-view.tsx", import.meta.url), "utf8");
const styles = readFileSync(new URL("../../styles/flow.css", import.meta.url), "utf8");

assert.match(executions, /onInspectRun: \(run: FlowRunRecord\) => void/, "Executions list should expose an inspect callback");
assert.match(executions, /Inspect/, "Each execution row should offer an Inspect action");
assert.match(executions, /onInspectRun\(run\)/, "Inspect should pass the selected run record to the parent");
assert.match(executions, /onRetryRun: \(run: FlowRunRecord, mode: "current" \| "original"\) => void/, "Executions list should expose retry mode wiring");
assert.match(executions, /run\.status === "failed" \|\| run\.status === "preview"/, "Only failed or preview executions should show retry");
assert.match(executions, /onRetryRun\(run, "current"\)/, "Retry current should pass the selected run record and mode to the parent");
assert.match(executions, /onRetryRun\(run, "original"\)/, "Retry original should pass the selected run record and mode to the parent");
assert.match(executions, /Retry current/, "Retry with current workflow should be visible on retryable execution rows");
assert.match(executions, /Retry original/, "Retry with original workflow should be visible when the run has a snapshot");
assert.match(executions, /run\.flowSnapshot/, "Retry original should require a stored workflow snapshot");
assert.match(executions, /onLoadRunData: \(run: FlowRunRecord\) => void/, "Executions list should expose debug/copy-to-editor wiring");
assert.match(executions, /run\.status === "failed" \? "Debug in editor" : "Copy to editor"/, "Execution data action should use n8n debug/copy labels");
assert.match(executions, /hasRunData/, "Execution data action should only appear when stored node data exists");
assert.match(executions, /!run\.redacted && run\.steps\.some/, "Redacted executions should not expose stored node data actions");
assert.match(executions, /onLoadRunData\(run\)/, "Execution data action should pass the selected run record to the parent");
assert.match(executions, /EXECUTION_MODE_LABEL/, "Execution rows should label manual vs production run mode");
assert.match(executions, /run\.mode \?\? "manual"/, "Execution rows should treat older records as manual mode");
assert.match(executions, /flow-exec-mode/, "Execution rows should render a mode badge");
assert.match(executions, /run\.redacted/, "Execution rows should expose redacted-run state");
assert.match(executions, /Redacted/, "Execution rows should show a Redacted badge when node details were not stored");
assert.match(executions, /type FlowExecutionStatusFilter/, "Executions should import the shared status filter type");
assert.match(executions, /useState<FlowExecutionStatusFilter>\("all"\)/, "Executions should keep the selected status filter locally");
assert.match(executions, /FLOW_EXECUTION_STARTED_FILTERS/, "Executions should offer n8n-style execution-start filters");
assert.match(executions, /useState<FlowExecutionStartedFilter>\("any"\)/, "Executions should keep the selected started filter locally");
assert.match(executions, /customKey/, "Executions should keep a custom-data key filter");
assert.match(executions, /customValue/, "Executions should keep a custom-data value filter");
assert.match(executions, /filterFlowRuns/, "Executions should derive a filtered run list through the shared filter helper");
assert.match(executions, /aria-pressed=\{filter === option\.value\}/, "Filter chips should expose pressed state");
assert.match(executions, /aria-pressed=\{startedFilter === option\.value\}/, "Started filter chips should expose pressed state");
assert.match(executions, /Started/, "Execution filters should label the started-time filter group");
assert.match(executions, /Saved data/, "Execution filters should label the custom-data filter group");
assert.match(executions, /run\.customData/, "Execution rows should render saved custom data chips");
assert.match(executions, /flowRunDurationLabel/, "Execution rows should derive elapsed duration from run timestamps");
assert.match(executions, /runs\.some\(\(run\) => run\.status === "running"\)/, "Execution rows should detect running executions for live duration refresh");
assert.match(executions, /window\.setInterval\(\(\) => setDurationNow\(new Date\(\)\), 1000\)/, "Running execution durations should refresh every second");
assert.match(executions, /window\.clearInterval/, "Running duration refresh should clean up its interval");
assert.match(executions, /Duration \$\{duration\}/, "Execution rows should display run duration in the metadata line");
assert.match(executions, /No executions match this filter/, "Filtered-empty state should be explicit");
assert.match(styles, /\.flow-exec-filters/, "Execution filters need layout styles");
assert.match(styles, /\.flow-exec-filter-group/, "Execution filter groups need layout styles");
assert.match(styles, /\.flow-exec-custom-input/, "Custom execution data filters need input styles");
assert.match(styles, /\.flow-exec-filter\.is-active/, "Active execution filter should be styled");
assert.match(styles, /\.flow-exec-mode-production/, "Production execution mode badge should be styled");
assert.match(styles, /\.flow-exec-custom-data/, "Custom execution data chips should be styled");
assert.match(view, /phasesFromRunSteps/, "Flow view should paint stored run step statuses when transcript markers are unavailable");
assert.match(view, /progress\.markersFound \? progress\.steps : activeRun\.steps/, "Flow view should inspect persisted node data when transcript markers are unavailable");
assert.match(view, /inspectRun/, "Flow view should have a named inspected-run handler");
assert.match(view, /retryRun/, "Flow view should have a named retry-run handler");
assert.match(view, /mode: "current" \| "original"/, "Flow view retry handler should model n8n retry modes");
assert.match(view, /mode === "original" \? run\.flowSnapshot : undefined/, "Original retry should use the execution's stored workflow snapshot");
assert.match(view, /loadRunData/, "Flow view should have a named debug/copy-to-editor handler");
assert.match(view, /setPinnedDataForNodes/, "Flow view should pin stored execution data into the editor");
assert.match(view, /onLoadRunData=\{loadRunData\}/, "Flow executions should delegate debug/copy-to-editor actions to Flow view");
assert.match(view, /onRetryRun=\{retryRun\}/, "Flow executions should delegate retry actions to Flow view");
assert.match(view, /setTab\("editor"\)/, "Inspecting a run should return the user to the editor canvas");

console.log("flow-executions.test.ts OK");
